name: Promote Python Package

on:
  repository_dispatch: # Trigger via Cloudsmith webhook
    types:
      - package_synchronized

env:
  CLOUDSMITH_NAMESPACE: ${{ vars.CLOUDSMITH_NAMESPACE }}
  CLOUDSMITH_STAGING_REPO: 'staging'
  CLOUDSMITH_PRODUCTION_REPO: 'production'
  CLOUDSMITH_SERVICE_SLUG: ${{ vars.CLOUDSMITH_SERVICE_SLUG }}
  PACKAGE_TAG: 'ready-for-production' # Tag required for production promotion

permissions:
  id-token: write # Necessary for GitHub to generate an OIDC token

jobs:
  promote:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Debug Webhook Payload
      - name: Log Webhook Payload
        run: |
          echo "Webhook Payload: ${{ toJson(github.event.client_payload) }}"
          cat $GITHUB_EVENT_PATH

      # Step 2: Install Cloudsmith CLI with OIDC
      - name: Install Cloudsmith CLI
        uses: cloudsmith-io/cloudsmith-cli-action@v1.0.1
        with:
          oidc-namespace: ${{ env.CLOUDSMITH_NAMESPACE }}
          oidc-service-slug: ${{ env.CLOUDSMITH_SERVICE_SLUG }}

      # Step 3: Retrieve Package Identifier
      - name: Retrieve Package Identifier
        run: |
          # Extract identifier from webhook payload
          IDENTIFIER="${{ github.event.client_payload.package_identifier }}"
          
          if [ -z "$IDENTIFIER" ]; then
            echo "Webhook failed to provide package identifier. Attempting query..."
            
            # Replace these dynamic parameters with appropriate values based on your workflow
            PACKAGE_NAME="${{ github.event.inputs.package_name }}"
            PACKAGE_VERSION="${{ github.event.inputs.package_version }}"
            
            if [ -z "$PACKAGE_NAME" ] || [ -z "$PACKAGE_VERSION" ]; then
              echo "PACKAGE_NAME and/or PACKAGE_VERSION are not provided."
              exit 1
            fi
            
            PACKAGE_QUERY="filename:${PACKAGE_NAME}-${PACKAGE_VERSION}.tar.gz"
            echo "Searching for package with query: $PACKAGE_QUERY"

            PACKAGE_DATA=$(cloudsmith list package ${{ env.CLOUDSMITH_NAMESPACE }}/${{ env.CLOUDSMITH_STAGING_REPO }} -q "$PACKAGE_QUERY" -F json)

            IDENTIFIER=$(echo "$PACKAGE_DATA" | jq -r '.data[0].identifier_perm')
            
            if [ -z "$IDENTIFIER" ] || [ "$IDENTIFIER" = "null" ]; then
              echo "Failed to find package identifier."
              exit 1
            fi
            
            echo "Fallback successfully found package identifier: $IDENTIFIER"
          fi

          echo "Using Package Identifier: $IDENTIFIER"

          # Save package identifier for subsequent steps
          echo "IDENTIFIER=$IDENTIFIER" >> $GITHUB_ENV

      # Step 4: Tag the Package with the ready-for-production Tag
      - name: Tag Package
        run: |
          # Tag the package with 'ready-for-production'
          cloudsmith tag add "${{ env.CLOUDSMITH_NAMESPACE }}/${{ env.CLOUDSMITH_STAGING_REPO }}/$IDENTIFIER" "${{ env.PACKAGE_TAG }}"
          if [ $? -ne 0 ]; then
            echo "Failed to tag the package with '${{ env.PACKAGE_TAG }}'."
            exit 1
          fi
          echo "Package successfully tagged with '${{ env.PACKAGE_TAG }}'."

      # Step 5: Promote All Tagged Packages to Production
      - name: Promote Tagged Packages
        run: |
          # Query packages tagged with 'ready-for-production'
          PACKAGE_QUERY="tags:${{ env.PACKAGE_TAG }}"
          echo "Searching for all packages tagged with query: $PACKAGE_QUERY"

          PACKAGE_DATA=$(cloudsmith list package ${{ env.CLOUDSMITH_NAMESPACE }}/${{ env.CLOUDSMITH_STAGING_REPO }} -q "$PACKAGE_QUERY" -F json)

          if [ -z "$PACKAGE_DATA" ] || [[ "$PACKAGE_DATA" == *"error"* ]]; then
            echo "No packages found with tag '${{ env.PACKAGE_TAG }}'. Exiting."
            exit 0
          fi

          IDENTIFIERS=$(echo "$PACKAGE_DATA" | jq -r '.data[].identifier_perm')
          echo "Found package identifiers tagged with '${{ env.PACKAGE_TAG }}': $IDENTIFIERS"

          # Promote each package
          for ID in $IDENTIFIERS; do
            cloudsmith mv --yes \
              ${{ env.CLOUDSMITH_NAMESPACE }}/${{ env.CLOUDSMITH_STAGING_REPO }}/$ID \
              ${{ env.CLOUDSMITH_PRODUCTION_REPO }}
            if [ $? -eq 0 ]; then
              echo "Successfully promoted package: $ID"
            else
              echo "Failed to promote package: $ID"
              exit 1
            fi
          done

          echo "All tagged packages promoted to '${{ env.CLOUDSMITH_PRODUCTION_REPO }}'."