name: Promote Python Package

on:
  repository_dispatch: # Trigger via Cloudsmith webhook
    types:
      - package_synchronized

env:
  CLOUDSMITH_NAMESPACE: ${{ vars.CLOUDSMITH_NAMESPACE }}
  CLOUDSMITH_STAGING_REPO: 'staging'
  CLOUDSMITH_PRODUCTION_REPO: 'production'
  CLOUDSMITH_SERVICE_SLUG: ${{ vars.CLOUDSMITH_SERVICE_SLUG }}
  PACKAGE_TAG: 'ready-for-production' # Tag used for production promotion

permissions:
  id-token: write # Necessary for GitHub to generate an OIDC token

jobs:
  promote:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Install Cloudsmith CLI
      - name: Install Cloudsmith CLI
        uses: cloudsmith-io/cloudsmith-cli-action@v1.0.1
        with:
          oidc-namespace: ${{ env.CLOUDSMITH_NAMESPACE }}
          oidc-service-slug: ${{ env.CLOUDSMITH_SERVICE_SLUG }}

      # Step 2: Extract Package Name and Version and Handle Underscores
      - name: Extract Package Name and Version
        run: |
          PACKAGE_NAME="${{ github.event.client_payload.package_name }}"
          PACKAGE_VERSION="${{ github.event.client_payload.package_version }}"

          # Replace dashes (-) with underscores (_) in PACKAGE_NAME
          FORMATTED_PACKAGE_NAME=$(echo "$PACKAGE_NAME" | sed 's/-/_/g')

          FULL_PACKAGE_FILENAME="${FORMATTED_PACKAGE_NAME}-${PACKAGE_VERSION}.tar.gz"

          if [ -z "$PACKAGE_NAME" ] || [ -z "$PACKAGE_VERSION" ]; then
            echo "PACKAGE_NAME or PACKAGE_VERSION is missing in the webhook payload."
            exit 1
          fi

          echo "PACKAGE_NAME=$PACKAGE_NAME" >> $GITHUB_ENV
          echo "PACKAGE_VERSION=$PACKAGE_VERSION" >> $GITHUB_ENV
          echo "FORMATTED_PACKAGE_NAME=$FORMATTED_PACKAGE_NAME" >> $GITHUB_ENV
          echo "FULL_PACKAGE_FILENAME=$FULL_PACKAGE_FILENAME" >> $GITHUB_ENV

          echo "Extracted PACKAGE_NAME: $PACKAGE_NAME"
          echo "Extracted PACKAGE_VERSION: $PACKAGE_VERSION"
          echo "Transformed FORMATTED_PACKAGE_NAME: $FORMATTED_PACKAGE_NAME"
          echo "Constructed FULL_PACKAGE_FILENAME: $FULL_PACKAGE_FILENAME"

      # Step 3: Retrieve Package Identifier
      - name: Retrieve Package Identifier
        run: |
          # Dynamically query for the package using the correct filename
          PACKAGE_QUERY="filename:${{ env.FULL_PACKAGE_FILENAME }}"
          echo "Querying Cloudsmith for package with filename: $PACKAGE_QUERY"

          PACKAGE_DATA=$(cloudsmith list package \
            ${{ env.CLOUDSMITH_NAMESPACE }}/${{ env.CLOUDSMITH_STAGING_REPO }} \
            -q "$PACKAGE_QUERY" -F json)

          IDENTIFIER=$(echo "$PACKAGE_DATA" | jq -r '.data[0].identifier_perm')

          if [ -z "$IDENTIFIER" ] || [ "$IDENTIFIER" = "null" ]; then
            echo "Failed to find package identifier in Cloudsmith response."
            exit 1
          fi

          echo "IDENTIFIER=$IDENTIFIER" >> $GITHUB_ENV
          echo "Found Package Identifier: $IDENTIFIER"

      # Step 4: Tag the Specific Package
      - name: Tag Package with ready-for-production Tag
        run: |
          cloudsmith tag add \
            "${{ env.CLOUDSMITH_NAMESPACE }}/${{ env.CLOUDSMITH_STAGING_REPO }}/$IDENTIFIER" \
            "${{ env.PACKAGE_TAG }}"

          if [ $? -ne 0 ]; then
            echo "Failed to tag the package with '${{ env.PACKAGE_TAG }}'."
            exit 1
          fi

          echo "Package successfully tagged with '${{ env.PACKAGE_TAG }}'."
      # Step 5: Promote Tagged Packages
      - name: Promote Tagged Packages to Production
        run: |
          echo "Searching for all packages tagged with '${{ env.PACKAGE_TAG }}'"

          # Query packages tagged with 'ready-for-production'
          PACKAGE_DATA=$(cloudsmith list package \
            ${{ env.CLOUDSMITH_NAMESPACE }}/${{ env.CLOUDSMITH_STAGING_REPO }} \
            -q "tags:${{ env.PACKAGE_TAG }}" \
            -F json)

          echo "Raw PACKAGE_DATA for Tagged Packages: $PACKAGE_DATA"

          # Extract package identifiers for promotion
          IDENTIFIERS=$(echo "$PACKAGE_DATA" | jq -r '.data[].identifier_perm')

          if [ -z "$IDENTIFIERS" ]; then
            echo "No packages found with tag '${{ env.PACKAGE_TAG }}'. Exiting."
            exit 0
          fi

          # Promote each package to production
          for ID in $IDENTIFIERS; do
            cloudsmith mv --yes \
              ${{ env.CLOUDSMITH_NAMESPACE }}/${{ env.CLOUDSMITH_STAGING_REPO }}/$ID \
              ${{ env.CLOUDSMITH_PRODUCTION_REPO }}

            if [ $? -eq 0 ]; then
              echo "Successfully promoted package: $ID"
            else
              echo "Failed to promote package: $ID"
              exit 1
            fi
          done

          echo "All tagged packages promoted to '${{ env.CLOUDSMITH_PRODUCTION_REPO }}'."