name: Promote Python Package

on:
  repository_dispatch:
    types:
      - package_synchronized  

env:
  CLOUDSMITH_NAMESPACE: ${{ vars.CLOUDSMITH_NAMESPACE }}
  CLOUDSMITH_STAGING_REPO: 'staging'
  CLOUDSMITH_PRODUCTION_REPO: 'production'
  CLOUDSMITH_SERVICE_SLUG: ${{ vars.CLOUDSMITH_SERVICE_SLUG }}
  PACKAGE_NAME: 'example_package'

permissions:
  id-token: write

jobs:
  promote:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Install Cloudsmith CLI with OIDC
      - name: Install Cloudsmith CLI
        uses: cloudsmith-io/cloudsmith-cli-action@v1.0.1
        with:
          oidc-namespace: ${{ env.CLOUDSMITH_NAMESPACE }}
          oidc-service-slug: ${{ env.CLOUDSMITH_SERVICE_SLUG }}

      # Step 2: Fetch the correct package identifier
      - name: Fetch Package Identifier
        run: |
          echo "Fetching the correct package identifier for ${PACKAGE_NAME}..."
          PACKAGE_DATA=$(cloudsmith list package ${{ env.CLOUDSMITH_NAMESPACE }}/${{ env.CLOUDSMITH_STAGING_REPO }} -q "name:${{ env.PACKAGE_NAME }}" -F json)
          PACKAGE_IDENTIFIER=$(echo "$PACKAGE_DATA" | jq -r '.data[0].identifier_perm')

          if [ -z "$PACKAGE_IDENTIFIER" ] || [ "$PACKAGE_IDENTIFIER" = "null" ]; then
            echo "Error: Failed to fetch the package identifier for ${PACKAGE_NAME}."
            exit 1
          fi

          echo "Found package identifier: $PACKAGE_IDENTIFIER"
          echo "PACKAGE_IDENTIFIER=$PACKAGE_IDENTIFIER" >> $GITHUB_ENV

      # Step 3: Tag the package with 'ready-for-production'
      - name: Tag Package as Ready for Production
        run: |
          FULL_PACKAGE_SLUG="${{ env.CLOUDSMITH_NAMESPACE }}/${{ env.CLOUDSMITH_STAGING_REPO }}/$PACKAGE_IDENTIFIER"
          echo "Debug: CLOUDSMITH_NAMESPACE=${{ env.CLOUDSMITH_NAMESPACE }}"
          echo "Debug: CLOUDSMITH_STAGING_REPO=${{ env.CLOUDSMITH_STAGING_REPO }}"
          echo "Debug: PACKAGE_IDENTIFIER=$PACKAGE_IDENTIFIER"
          echo "Debug: FULL_PACKAGE_SLUG=$FULL_PACKAGE_SLUG"

          echo "Tagging package $FULL_PACKAGE_SLUG with 'ready-for-production'..."
          cloudsmith tag add $FULL_PACKAGE_SLUG ready-for-production || {
            echo "Failed to add tag. Please verify the package identifier and repository details."
            exit 1
          }

      # Step 4: Query for all packages tagged with 'ready-for-production' and promote them
      - name: Query and Promote Packages
        run: |
          # Query for all packages tagged with 'ready-for-production'
          echo "Querying for packages tagged with 'ready-for-production'..."
          PACKAGE_DATA=$(cloudsmith list package ${{ env.CLOUDSMITH_NAMESPACE }}/${{ env.CLOUDSMITH_STAGING_REPO }} -q "tag:ready-for-production" -F json)

          # Extract all package identifiers using jq
          IDENTIFIERS=$(echo "$PACKAGE_DATA" | jq -r '.data[].identifier_perm')

          if [ -z "$IDENTIFIERS" ]; then
            echo "No packages found with the 'ready-for-production' tag."
            exit 0
          fi

          echo "Found packages to promote: $IDENTIFIERS"

          # Promote each package to the production repository
          for IDENTIFIER in $IDENTIFIERS; do
            echo "Promoting package $IDENTIFIER to production..."
            cloudsmith mv --yes \
              ${{ env.CLOUDSMITH_NAMESPACE }}/${{ env.CLOUDSMITH_STAGING_REPO }}/$IDENTIFIER \
              ${{ env.CLOUDSMITH_PRODUCTION_REPO }}
          done
        shell: bash
